name: Release workflow
on: 
  release: 
    types: [published]
  workflow_dispatch:

jobs:
  create-packages:
    name: Build api packages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create packages
        run: scripts/build.sh
        shell: sh
      - name: Archive typescript-fetch artifact
        uses: actions/upload-artifact@v2
        with:
          name: typescript-fetch-artifact
          path: lib/typescript-fetch
          retention-days: 1

  publish-typescript-fetch:
    name: Publish typescript-fetch package to npm
    runs-on: ubuntu-20.04
    needs: create-packages
    environment: production
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: typescript-fetch-artifact
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org
          always-auth: true
      - name: build npm package
        run: yarn
      - name: expose token
        run: echo "token ${{ secrets.NPM_CI_AUTH_TOKEN }}"
      - name: Publish to npm
        run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_CI_AUTH_TOKEN }}
      
